@echo off
echo [*] Installing dependencies...
echo [+] Installing fzf...
winget install -e --id junegunn.fzf
echo [+] Installing fd...
winget install -e --id sharkdp.fd
echo [+] Installing bat...
winget install -e --id sharkdp.bat
echo [!] Done
